name: eldealer
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  animate_do: ^4.2.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  envied: ^1.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_bloc: ^9.1.1
  delightful_toast: ^1.1.0
  flutter_svg: ^2.1.0
  freezed: 2.5.7
  get_it: ^8.0.3
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.4.0
  scrollable_clean_calendar: ^1.5.0
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.0+1
  flutter_launcher_icons: ^0.14.4
  dots_indicator: ^4.0.1
  

dev_dependencies:
  build_runner: ^2.5.4
  envied_generator: ^1.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true

  assets:
    - asset/images/
    - asset/svgs/
    - asset/translations/
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/images/app_logo_without_bg.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
 