name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - run: pod repo update
        working-directory: ios

      - name: Build ipa
        run: flutter build ipa --release --no-codesign --target-platform=ios

      - name: Upload ipa
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/ipa/Runner.ipa